languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = ""
  # logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "Mofu"
  email = ""
  image = "img/bluemoon.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://x.com/mwa_mofu" },
    { github = "https://github.com/mimimimirai" },
  ]