languageCode = "ja"
languageName = "日本語"
weight = 3
title = "Mysite"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = ""
  logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "Mofu"
  email = ""
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://x.com/mwa_mofu" },
    { github = "https://github.com/mimimimirai" },
  ]