languageCode = "ja"
languageName = "日本語"
weight = 3
title = "Mysite"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = ""
  # logo = "img/moon.png" # 左上のロゴアイコンを削除
  description = ""

[params.author]
  name = "Mofu"
  email = ""
  image = "img/bluemoon.png" # サイト中央の画像をbluemoon.pngに設定
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://x.com/mwa_mofu" },
    { github = "https://github.com/mimimimirai" },
  ]