# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Notion"
  url = "https://www.notion.so/b8499c92a01b4cd7ad829ff66b49304be"  # Replace with your Notion public page URL
  weight = 10

[[main]]
  name = "note"
  url = "https://note.com/cool_pipit9875"
  weight = 15

[[main]]
  name = "Examples"
  weight = 20

[[main]]
  name = "Samples"
  parent = "Examples"
  pageRef = "samples"
  weight = 16

[[main]]
  name = "Showcase"
  parent = "Examples"
  pageRef = "examples"
  weight = 30

[[main]]
  name = "Recipes"
  parent = "Examples"
  pageRef = "guides"
  weight = 40

[[main]]
  name = "Users"
  pageRef = "users"
  weight = 90

[[main]]
  name = "Organization"
  url = "https://www.wantedly.com/projects/2231861"
  weight = 100

[[main]]
  identifier = "x"
  pre = "x-twitter"
  url = "https://x.com/mwa_mofu"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/mimimimirai"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
