# -- メインメニュー --
# メインメニューはページトップのヘッダーに表示されます。
# 利用可能なパラメーターは name, pageRef, page, url, title, weight です。
# 
# 最もシンプルなメニュー設定はこちらです:
#   name = このメニューリンクに表示される名前
#   pageRef = ページやセクションのリンクに利用される識別子
#
# デフォルトでは、メニューはアルファベット順に並べられます。
# これは、 weight value で上書き可能です。
# このメニューは weight が低い値から高い値に順に表示されます。

[[main]]
  name = "Notion"
  url = "https://www.notion.so/b8499c92a01b4cd7ad829ff66b49304b"  # Notionの公開ページURLに置き換えてください
  weight = 10

[[main]]
  name = "note"
  url = "https://note.com/cool_pipit9875"
  weight = 15

[[main]]
  name = "例"
  weight = 20

[[main]]
  name = "サンプル"
  parent = "例"
  pageRef = "samples"
  weight = 16

[[main]]
  name = "ショーケース"
  parent = "例"
  pageRef = "examples"
  weight = 30

[[main]]
  name = "レシピ"
  parent = "例"
  pageRef = "guides"
  weight = 40

[[main]]
  name = "ユーザー"
  pageRef = "users"
  weight = 90

[[main]]
  name = "所属"
  url = "https://www.wantedly.com/projects/2231861"
  weight = 100


[[main]]
  identifier = "x"
  pre = "x-twitter"
  url = "https://x.com/mwa_mofu"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/mimimimirai"
  weight = 400


# -- フッターメニュー --
# このフッターメニューはページ下部のコピーライト表示の前に表示されます。
# 上記のメインメニューと同様に設定できます。

 [[footer]]
   name = "タグ"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Mofu"
   pageRef = "authors"
   weight = 20
